export interface AntiPattern {
  name: string;
  slug: string;
  kind: "AI-slop" | "Quality";
  detection: "Lint" | "Type-check" | "Review";
  scope: string;
  category: string;
  categorySlug: string;
}

export function parseAntiPatterns(): AntiPattern[] {
  // Parsed from the README index table
  const raw: [string, string, string, string, string, string][] = [
    ["AI-review-noise", "review-burden#ai-review-noise", "AI-slop", "Review", "Universal", "Review burden"],
    ["All-caps ceremony constants", "stylistic-tells#all-caps-ceremony-constants", "AI-slop", "Lint", "Universal", "Stylistic tells"],
    ["Assumption propagation", "security-and-correctness#assumption-propagation", "Quality", "Review", "Universal", "Security & correctness"],
    ["Barrel index.ts re-exports everything", "file-organization#barrel-index-ts-re-exports-everything", "Quality", "Lint", "Lang:TS", "File organization"],
    ["Builder for two fields", "gratuitous-abstraction#builder-for-two-fields", "AI-slop", "Review", "Universal", "Gratuitous abstraction"],
    ["Bypassing framework CSRF/CORS", "security-and-correctness#bypassing-framework-csrf-cors", "Quality", "Lint", "Universal", "Security & correctness"],
    ["Catch-all test", "testing-slop#catch-all-test", "AI-slop", "Lint", "Universal", "Testing slop"],
    ["Clean-Architecture-7-layers-for-CRUD", "architectural-slop#clean-architecture-7-layers-for-crud", "AI-slop", "Review", "Universal", "Architectural slop"],
    ["Commented-out 'just in case' code", "comment-slop#commented-out-just-in-case-code", "AI-slop", "Lint", "Universal", "Comment slop"],
    ["Comprehension debt", "review-burden#comprehension-debt", "Quality", "Review", "Universal", "Review burden"],
    ["Console.log as observability strategy", "stylistic-tells#console-log-as-observability-strategy", "AI-slop", "Lint", "Universal", "Stylistic tells"],
    ["const noop = () => {}", "boilerplate-and-ceremony#const-noop-", "AI-slop", "Lint", "Universal", "Boilerplate"],
    ["Constructor-that-only-assigns-fields", "boilerplate-and-ceremony#constructor-that-only-assigns-fields", "AI-slop", "Lint", "Universal", "Boilerplate"],
    ["Convergence cliff", "review-burden#convergence-cliff", "Quality", "Review", "Universal", "Review burden"],
    ["Copy-paste architecture", "architectural-slop#copy-paste-architecture", "Quality", "Lint", "Universal", "Architectural slop"],
    ["Dead-code accumulation", "review-burden#dead-code-accumulation", "Quality", "Lint", "Universal", "Review burden"],
    ["Deep-nested paranoid layering", "file-organization#deep-nested-paranoid-layering", "AI-slop", "Lint", "Universal", "File organization"],
    ["Deprecated-suggestion", "dependency-slop#deprecated-suggestion", "AI-slop", "Lint", "Universal", "Dependency slop"],
    ["Drive-by one-shot PR", "review-burden#drive-by-one-shot-pr", "AI-slop", "Review", "Universal", "Review burden"],
    ["Emoji comments", "comment-slop#emoji-comments", "AI-slop", "Lint", "Universal", "Comment slop"],
    ["Emoji in log messages", "stylistic-tells#emoji-in-log-messages", "AI-slop", "Lint", "Universal", "Stylistic tells"],
    ["Empty interface / marker class", "boilerplate-and-ceremony#empty-interface-marker-class", "Quality", "Lint", "Universal", "Boilerplate"],
    ["Empty TODO", "comment-slop#empty-todo", "AI-slop", "Lint", "Universal", "Comment slop"],
    ["Enterprise-patterns-in-scripts", "architectural-slop#enterprise-patterns-in-scripts", "AI-slop", "Review", "Universal", "Architectural slop"],
    ["Event-driven-for-synchronous-workflow", "architectural-slop#event-driven-for-synchronous-workflow", "Quality", "Review", "Universal", "Architectural slop"],
    ["Fabricated API call", "security-and-correctness#fabricated-api-call", "AI-slop", "Lint", "Universal", "Security & correctness"],
    ["Factory/Strategy/Provider spam", "gratuitous-abstraction#factory-strategy-provider-spam", "AI-slop", "Review", "Universal", "Gratuitous abstraction"],
    ["Fake-data / lying tests", "testing-slop#fake-data-lying-tests", "AI-slop", "Review", "Universal", "Testing slop"],
    ["Fallback-masks-bug", "over-defensive#fallback-masks-bug", "AI-slop", "Review", "Universal", "Over-defensive"],
    ["Generic-name-where-specific-needed", "naming-slop#generic-name-where-specific-needed", "AI-slop", "Lint", "Universal", "Naming slop"],
    ["God-prompt-component", "architectural-slop#god-prompt-component", "AI-slop", "Lint", "Universal", "Architectural slop"],
    ["GraphQL-for-two-endpoints", "architectural-slop#graphql-for-two-endpoints", "AI-slop", "Review", "Universal", "Architectural slop"],
    ["Happy-path utopia", "over-defensive#happy-path-utopia", "Quality", "Review", "Universal", "Over-defensive"],
    ["Hardcoded secret in source", "security-and-correctness#hardcoded-secret-in-source", "Quality", "Lint", "Universal", "Security & correctness"],
    ["Heavyweight-for-trivial", "dependency-slop#heavyweight-for-trivial", "AI-slop", "Review", "Universal", "Dependency slop"],
    ["Hungarian resurgence", "naming-slop#hungarian-resurgence", "AI-slop", "Lint", "Universal", "Naming slop"],
    ["if __name__ == '__main__' on library modules", "boilerplate-and-ceremony#if-name-main-on-library-modules", "AI-slop", "Lint", "Lang:Python", "Boilerplate"],
    ["Impl-named test", "testing-slop#impl-named-test", "Quality", "Lint", "Universal", "Testing slop"],
    ["INFO-on-every-entry", "stylistic-tells#info-on-every-entry", "AI-slop", "Lint", "Universal", "Stylistic tells"],
    ["Inconsistent casing shifts mid-function", "naming-slop#inconsistent-casing-shifts-mid-function", "AI-slop", "Lint", "Universal", "Naming slop"],
    ["Line-narration", "comment-slop#line-narration", "AI-slop", "Lint", "Universal", "Comment slop"],
    ["Lodash-for-isEmpty", "dependency-slop#lodash-for-isempty", "AI-slop", "Lint", "Lang:JS", "Dependency slop"],
    ["JSDoc-that-mirrors-types", "comment-slop#jsdoc-that-mirrors-types", "AI-slop", "Lint", "Lang:TS", "Comment slop"],
    ["Manager/Helper/Service/Handler/Util suffix proliferation", "naming-slop#manager-helper-service-handler-util-suffix-proliferation", "AI-slop", "Lint", "Universal", "Naming slop"],
    ["Markdown in docstrings", "stylistic-tells#markdown-in-docstrings", "AI-slop", "Lint", "Universal", "Stylistic tells"],
    ["Math.random for security tokens", "security-and-correctness#math-random-for-security-tokens", "Quality", "Lint", "Universal", "Security & correctness"],
    ["Meta-narration ('Let's... Now we...')", "comment-slop#meta-narration-lets-now-we", "AI-slop", "Lint", "Universal", "Comment slop"],
    ["Microservices-for-a-function", "architectural-slop#microservices-for-a-function", "AI-slop", "Review", "Universal", "Architectural slop"],
    ["Mock-the-thing-under-test", "testing-slop#mock-the-thing-under-test", "Quality", "Review", "Universal", "Testing slop"],
    ["N+1 query", "security-and-correctness#n-1-query", "Quality", "Review", "Universal", "Security & correctness"],
    ["No pagination / unbounded fetch", "security-and-correctness#no-pagination-unbounded-fetch", "Quality", "Review", "Universal", "Security & correctness"],
    ["Optional-chaining paranoia", "over-defensive#optional-chaining-paranoia", "AI-slop", "Type-check", "Lang:TS", "Over-defensive"],
    ["Orphan migration / schema drift", "file-organization#orphan-migration-schema-drift", "Quality", "Lint", "Universal", "File organization"],
    ["Outdated API version", "dependency-slop#outdated-api-version", "AI-slop", "Review", "Universal", "Dependency slop"],
    ["Over-destructure-with-defaults", "gratuitous-abstraction#over-destructure-with-defaults", "AI-slop", "Review", "Lang:JS", "Gratuitous abstraction"],
    ["Over-split one-function-per-file", "file-organization#over-split-one-function-per-file", "AI-slop", "Lint", "Universal", "File organization"],
    ["Paranoid try/catch everywhere", "over-defensive#paranoid-try-catch-everywhere", "AI-slop", "Lint", "Universal", "Over-defensive"],
    ["Phantom assertion", "testing-slop#phantom-assertion", "AI-slop", "Lint", "Universal", "Testing slop"],
    ["PR-slop / verbose-LLM-description", "review-burden#pr-slop-verbose-llm-description", "AI-slop", "Lint", "Universal", "Review burden"],
    ["Premature generics", "gratuitous-abstraction#premature-generics", "AI-slop", "Review", "Universal", "Gratuitous abstraction"],
    ["Provider/Context-for-one-value", "gratuitous-abstraction#provider-context-for-one-value", "AI-slop", "Lint", "Lang:TS", "Gratuitous abstraction"],
    ["Pydantic-for-a-dict", "boilerplate-and-ceremony#pydantic-for-a-dict", "AI-slop", "Review", "Lang:Python", "Boilerplate"],
    ["Redundant existence checks", "over-defensive#redundant-existence-checks", "AI-slop", "Lint", "Universal", "Over-defensive"],
    ["Redux-for-local-state", "architectural-slop#redux-for-local-state", "AI-slop", "Review", "Lang:TS", "Architectural slop"],
    ["README-on-trivial-helper", "comment-slop#readme-on-trivial-helper", "AI-slop", "Lint", "Universal", "Comment slop"],
    ["Re-validation at every layer / phantom validation", "over-defensive#re-validation-at-every-layer-phantom-validation", "AI-slop", "Review", "Universal", "Over-defensive"],
    ["Resume-padding / green-square farming", "review-burden#resume-padding-green-square-farming", "AI-slop", "Review", "Universal", "Review burden"],
    ["Section divider comments", "comment-slop#section-divider-comments", "AI-slop", "Lint", "Universal", "Comment slop"],
    ["Single-use interface", "gratuitous-abstraction#single-use-interface", "AI-slop", "Lint", "Universal", "Gratuitous abstraction"],
    ["Slop-loop addiction", "review-burden#slop-loop-addiction", "AI-slop", "Review", "Universal", "Review burden"],
    ["Slopsquatting / hallucinated import", "security-and-correctness#slopsquatting-hallucinated-import", "AI-slop", "Lint", "Universal", "Security & correctness"],
    ["Snapshot-of-meaningless-output", "testing-slop#snapshot-of-meaningless-output", "AI-slop", "Lint", "Universal", "Testing slop"],
    ["SQL-string-concat", "security-and-correctness#sql-string-concat", "Quality", "Lint", "Universal", "Security & correctness"],
    ["Stanford 'insecure-but-confident' effect", "security-and-correctness#stanford-insecure-but-confident-effect", "Quality", "Review", "Universal", "Security & correctness"],
    ["Swallowed exception", "over-defensive#swallowed-exception", "AI-slop", "Lint", "Universal", "Over-defensive"],
    ["Tautological test", "testing-slop#tautological-test", "AI-slop", "Lint", "Universal", "Testing slop"],
    ["Test duplicates production logic", "testing-slop#test-duplicates-production-logic", "Quality", "Review", "Universal", "Testing slop"],
    ["Trivial getters/setters", "boilerplate-and-ceremony#trivial-getters-setters", "AI-slop", "Lint", "Universal", "Boilerplate"],
    ["Tutorial-scale descriptive names", "naming-slop#tutorial-scale-descriptive-names", "AI-slop", "Lint", "Universal", "Naming slop"],
    ["Unbounded goroutine / unbounded worker", "security-and-correctness#unbounded-goroutine-unbounded-worker", "Quality", "Review", "Lang:Go", "Security & correctness"],
    ["Unnecessary class wrapping functions", "boilerplate-and-ceremony#unnecessary-class-wrapping-functions", "AI-slop", "Review", "Universal", "Boilerplate"],
    ["UserData / UserInfo / UserDetails divergence", "naming-slop#userdata-userinfo-userdetails-divergence", "AI-slop", "Review", "Universal", "Naming slop"],
    ["utils.ts / helpers.ts / common.ts dumping ground", "file-organization#utils-ts-helpers-ts-common-ts-dumping-ground", "AI-slop", "Lint", "Universal", "File organization"],
    ["Verbose bulleted error messages", "stylistic-tells#verbose-bulleted-error-messages", "AI-slop", "Lint", "Universal", "Stylistic tells"],
    ["Wrapper-that-forwards-args", "gratuitous-abstraction#wrapper-that-forwards-args", "Quality", "Lint", "Universal", "Gratuitous abstraction"],
    ["/constants/ for two values", "file-organization#constants-for-two-values", "AI-slop", "Review", "Universal", "File organization"],
    ["Over-capitalized success/error strings", "stylistic-tells#over-capitalized-success-error-strings", "AI-slop", "Lint", "Universal", "Stylistic tells"],
  ];

  return raw.map(([name, slug, kind, detection, scope, category]) => ({
    name,
    slug,
    kind: kind as AntiPattern["kind"],
    detection: detection as AntiPattern["detection"],
    scope,
    category,
    categorySlug: slug.split("#")[0],
  }));
}
